name: enable codecov
on: 
  pull_request:
    branches:
      - main
      - dev

jobs:
  codecov-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with: 
          fetch-depth: 0
      - name: set up nodejs
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14

      - name: setup project
        run: |
          npm install

      - name: Unit Test
        run: |
          npm run test

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          commit_parent: 'dev'
          override_branch: 'dev'
          verbose: true



